# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: goji_interview
      POSTGRES_USER: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
    ports:
      - 5000:5000